🗃 Modified: bin/setup_lua  🗃

diff --git a/bin/setup_lua b/bin/setup_lua
--- a/bin/setup_lua
+++ b/bin/setup_lua
@@ -65,21 +65,20 @@ main() {
   export LUAVER_HOME LUAROCKS_BIN PATH
   printf_blue "Initializing LUA Setup"
   [[ -d "$LUAVER_HOME/.git" ]] || rm -Rf "$LUAVER_HOME" &>/dev/null
-  printf_green "Downloading luaver from $GITREPO"
-  if [[ -d "$LUAVER_HOME/.git" ]]; then
-    git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null
-    git -C "$LUAVER_HOME" fetch origin &>/dev/null &&
-      git -C "$LUAVER_HOME" pull &>/dev/null &&
-      git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null &&
-      printf_blue "Downloaded luaver from $GITREPO" || printf_exit "Failed to download the repo" >&2
-  elif git clone "$GITREPO" -q "$LUAVER_HOME" &>/dev/null; then
-    printf_blue "Downloaded luaver from $GITREPO"
-  else
-    printf_exit "Failed to download the repo" >&2
-  fi
+  # printf_green "Downloading luaver from $GITREPO"
+  # if [[ -d "$LUAVER_HOME/.git" ]]; then
+  #   git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null
+  #   git -C "$LUAVER_HOME" fetch origin &>/dev/null &&
+  #     git -C "$LUAVER_HOME" pull &>/dev/null &&
+  #     git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null &&
+  #     printf_blue "Downloaded luaver from $GITREPO" || printf_exit "Failed to download the repo" >&2
+  # elif git clone "$GITREPO" -q "$LUAVER_HOME" &>/dev/null; then
+  #   printf_blue "Downloaded luaver from $GITREPO"
+  # else
+  #   printf_exit "Failed to download the repo" >&2
+  # fi
   printf_green "Installing luaver to $LUAVER_HOME"
-  cd "$LUAVER_HOME" && bash -c "$LUAVER_HOME/install.sh" &>/dev/null
-  [[ -f "$LUAVER_HOME/luaver" ]] && source "$LUAVER_HOME/luaver" &&
+  type luaver &>/dev/null &&
     printf_green "Installing LUA $version" &&
     luaver install $version &&
     luaver install-luarocks 3.8.0 &&
