🗃️ Committing everything that changed 🗃️
bin/setup_lua

diff --git a/bin/setup_lua b/bin/setup_lua
--- a/bin/setup_lua
+++ b/bin/setup_lua
@@ -6,7 +6,7 @@ HOME="${USER_HOME:-${HOME}}"
 SRC_DIR="${BASH_SOURCE%/*}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 #set opts
-trap 'exitCode=${exitCode:-$?};[[ -d "$HOME/tmp/rvm_install" ]] && rm -Rf "$HOME/tmp/rvm_install" &>/dev/null' EXIT
+trap 'exitCode=${exitCode:-$?};[ -d "$HOME/tmp/rvm_install" ] && rm -Rf "$HOME/tmp/rvm_install" &>/dev/null' EXIT
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ##@Version       : 031520211551-git
@@ -61,41 +61,49 @@ main() {
   local LUAVER_HOME="${LUAVER_HOME:-$HOME/.local/share/misc/plugins/luaver}"
   local LUAROCKS_BIN="${LUAROCKS_BIN:-$HOME/.local/share/lua/luarocks/bin}"
   local PATH="$LUAROCKS_BIN:$PATH"
+  local logFile="${TMP:-/tmp}/setup_lua.log"
   local version="${lua_version:-5.4.3}"
   local rversion="${rocks_version:-3.8.0}"
   local jversion="${jit_version:-2.0.5}"
   luaver_bin_file="$(lslink --raw ~/.local/bin/luaver)"
   export LUAVER_HOME LUAROCKS_BIN PATH
   printf_cyan "Installing luaver to $LUAVER_HOME"
-  [[ -d "$LUAVER_HOME/.git" ]] || rm -Rf "$LUAVER_HOME" &>/dev/null
+  [ -d "$LUAVER_HOME/.git" ] || rm -Rf "$LUAVER_HOME" &>/dev/null
   printf_green "Downloading luaver from $GITREPO"
-  if [[ -d "$LUAVER_HOME/.git" ]]; then
+  if [ -d "$LUAVER_HOME/.git" ]; then
     git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null
     git -C "$LUAVER_HOME" fetch origin &>/dev/null &&
       git -C "$LUAVER_HOME" pull &>/dev/null &&
       git -C "$LUAVER_HOME" reset --hard origin/master &>/dev/null &&
       printf_blue "Downloaded luaver from $GITREPO" || printf_exit "Failed to download the repo" >&2
-  elif git clone "$GITREPO" -q "$LUAVER_HOME" &>/dev/null; then
+  elif git clone "$GITREPO" "$LUAVER_HOME" -q &>/dev/null; then
     printf_blue "Downloaded luaver from $GITREPO"
   else
     printf_exit "Failed to download the repo" >&2
   fi
-  [[ -f "$luaver_bin_file" ]] && [[ -f "$LUAVER_HOME/luaver" ]] && cp -Rf "$luaver_bin_file" "$LUAVER_HOME/luaver"
-  type luaver &>/dev/null &&
+  if [ -f "$luaver_bin_file" ] && [ -f "$LUAVER_HOME/luaver" ] && [ "$luaver_bin_file" != "$LUAVER_HOME/luaver" ]; then
+    ln -sf "$LUAVER_HOME/luaver" "$luaver_bin_file"
+  fi
+  if type luaver &>/dev/null; then
     printf_green "Installing lua version: $version" &&
-    luaver -f install $version &>/dev/null &&
-    luaver set-default $version &>/dev/null &&
-    luaver -f install-luarocks $rversion &>/dev/null &&
-    luaver install-luajit $jversion &>/dev/null &&
-    luaver set-default $version &>/dev/null || error=true
-  get_ver="$(luaver current | grep 'lua' | grep '^')"
-  get_rver="$(luaver set-default-luarocks 3.8.0 2>&1 | tr ' ' '\n' | grep '[0-9].[0-9]' | grep '^')"
-  if [[ -n "$get_ver" ]] && [[ -n "$get_rver" ]] && [[ -z "$error" ]]; then
-    printf_green "Finished installing lua! $get_ver"
-    exitCode=0
+      luaver -f install "$version" >>"$logFile" 2>"$logFile.err" &&
+      luaver set-default "$version" >>"$logFile" 2>"$logFile.err" &&
+      luaver -f install-luarocks "$rversion" >>"$logFile" 2>"$logFile.err" &&
+      luaver install-luajit "$jversion" >>"$logFile" 2>"$logFile.err" &&
+      luaver set-default "$version" >>"$logFile" 2>"$logFile.err" || error="true"
+    get_ver="$(luaver current | grep 'lua' | grep '^')"
+    get_rver="$(luaver set-default-luarocks 3.8.0 2>&1 | tr ' ' '\n' | grep '[0-9].[0-9]' | grep '^')"
+    if [ -n "$get_ver" ] && [ -n "$get_rver" ] && [ -z "$error" ]; then
+      printf_green "Finished installing lua! $get_ver"
+      [ -f "$logFile" ] && rm -Rf "$logFile"
+      [ -f "$logFile.err" ] && rm -Rf "$logFile.err"
+      exitCode=0
+    else
+      printf_exit "Installation of lua has failed: log saved to $logFile.err" >&2
+      exitCode=1
+    fi
   else
-    printf_exit "Installation of lua has failed" >&2
-    exitCode=1
+    printf_exit "Failed to setup luaver"
   fi
   return "${exitCode:-$?}"
 }
